from app.models.schemas import CareProfile, PlantCatalogItem


def make_plant(
    common_name: str,
    species_name: str,
    difficulty: str,
    tags: list[str],
    water_interval_days: int,
    light: str,
    humidity: str,
    fertilizer: str,
    soil: str,
    notes: list[str],
) -> PlantCatalogItem:
    return PlantCatalogItem(
        common_name=common_name,
        species_name=species_name,
        difficulty=difficulty,
        tags=tags,
        care_profile=CareProfile(
            water_interval_days=water_interval_days,
            light=light,
            humidity=humidity,
            fertilizer=fertilizer,
            soil=soil,
            notes=notes,
        ),
    )


PLANT_CATALOG = [
    make_plant("Monstera", "Monstera deliciosa", "easy", ["indoor", "foliage"], 7, "bright indirect", "medium-high", "monthly in spring/summer", "well-draining aroid mix", ["Wipe leaves monthly", "Support with a moss pole"]),
    make_plant("Snake Plant", "Dracaena trifasciata", "easy", ["indoor", "low-light"], 14, "low to bright indirect", "low", "every 6 weeks", "cactus or airy potting mix", ["Let soil dry fully", "Avoid overwatering"]),
    make_plant("Pothos", "Epipremnum aureum", "easy", ["indoor", "vine"], 7, "medium to bright indirect", "medium", "monthly", "well-draining potting mix", ["Trim vines to encourage fullness", "Tolerates lower light"]),
    make_plant("Peace Lily", "Spathiphyllum wallisii", "moderate", ["indoor", "flowering"], 5, "medium indirect", "high", "monthly", "rich well-draining mix", ["Leaves droop when thirsty", "Keep away from hot drafts"]),
    make_plant("ZZ Plant", "Zamioculcas zamiifolia", "easy", ["indoor", "low-maintenance"], 14, "low to bright indirect", "low", "every 8 weeks", "well-draining mix", ["Stores water in rhizomes", "Rotate for even growth"]),
    make_plant("Spider Plant", "Chlorophytum comosum", "easy", ["indoor", "pet-friendly"], 6, "bright indirect", "medium", "monthly", "light potting mix", ["Brown tips often mean mineral buildup", "Flush soil occasionally"]),
    make_plant("Rubber Plant", "Ficus elastica", "moderate", ["indoor", "tree"], 8, "bright filtered", "medium", "monthly", "well-draining mix", ["Avoid frequent relocation", "Wipe glossy leaves"]),
    make_plant("Fiddle Leaf Fig", "Ficus lyrata", "advanced", ["indoor", "statement"], 7, "bright indirect", "medium", "monthly", "chunky well-draining mix", ["Needs consistent conditions", "Turn pot weekly"]),
    make_plant("Heartleaf Philodendron", "Philodendron hederaceum", "easy", ["indoor", "vine"], 7, "medium indirect", "medium", "monthly", "well-draining mix", ["Great for shelves and trailing baskets"]),
    make_plant("Areca Palm", "Dypsis lutescens", "moderate", ["indoor", "palm"], 6, "bright indirect", "high", "monthly", "peaty well-draining mix", ["Mist in dry rooms", "Remove yellow fronds at the base"]),
    make_plant("Calathea", "Goeppertia orbifolia", "advanced", ["indoor", "foliage"], 4, "medium indirect", "high", "monthly diluted", "moisture-retentive but airy mix", ["Use filtered water if possible", "Avoid direct sun"]),
    make_plant("Chinese Evergreen", "Aglaonema commutatum", "easy", ["indoor", "foliage"], 8, "low to medium indirect", "medium", "every 6 weeks", "well-draining indoor mix", ["Colorful varieties need more light"]),
    make_plant("Bird of Paradise", "Strelitzia nicolai", "moderate", ["indoor", "tropical"], 7, "bright direct/indirect", "medium", "every 2 weeks in growth season", "rich well-draining mix", ["Large leaves split naturally", "Needs strong light"]),
    make_plant("Aloe Vera", "Aloe barbadensis miller", "easy", ["succulent", "medicinal"], 14, "bright direct", "low", "every 8 weeks", "cactus mix", ["Water deeply then dry", "Use terra cotta if possible"]),
    make_plant("Jade Plant", "Crassula ovata", "easy", ["succulent", "indoor"], 12, "bright direct", "low", "every 8 weeks", "cactus mix", ["Pinch tips to branch out"]),
    make_plant("Echeveria", "Echeveria elegans", "moderate", ["succulent", "rosette"], 12, "bright direct", "low", "every 8 weeks", "gritty succulent mix", ["Keep water out of the rosette center"]),
    make_plant("Haworthia", "Haworthiopsis attenuata", "easy", ["succulent", "compact"], 12, "bright indirect", "low", "every 8 weeks", "succulent mix", ["Excellent desk plant"]),
    make_plant("Christmas Cactus", "Schlumbergera truncata", "moderate", ["cactus", "flowering"], 8, "bright indirect", "medium", "monthly during growth", "light airy mix", ["Needs longer nights to bloom"]),
    make_plant("Barrel Cactus", "Echinocactus grusonii", "moderate", ["cactus", "sun-loving"], 18, "full sun", "low", "twice during warm season", "sandy cactus mix", ["Do not let water sit around the roots"]),
    make_plant("Tulsi", "Ocimum tenuiflorum", "moderate", ["herb", "balcony"], 3, "full sun", "medium", "every 2 weeks", "fertile well-draining mix", ["Pinch flowers to extend leaf harvest"]),
    make_plant("Basil", "Ocimum basilicum", "easy", ["herb", "edible"], 3, "full sun", "medium", "every 2 weeks", "rich well-draining mix", ["Harvest regularly to keep it bushy"]),
    make_plant("Mint", "Mentha spicata", "easy", ["herb", "edible"], 3, "partial sun", "medium-high", "monthly", "moisture-retentive mix", ["Best grown in its own pot"]),
    make_plant("Rosemary", "Salvia rosmarinus", "moderate", ["herb", "edible"], 6, "full sun", "low", "monthly diluted", "sandy well-draining mix", ["Avoid soggy soil"]),
    make_plant("Thyme", "Thymus vulgaris", "easy", ["herb", "edible"], 5, "full sun", "low", "monthly diluted", "gritty herb mix", ["Trim often to prevent woodiness"]),
    make_plant("Oregano", "Origanum vulgare", "easy", ["herb", "edible"], 4, "full sun", "medium", "monthly diluted", "well-draining herb mix", ["Cut back before flowering for best flavor"]),
    make_plant("Parsley", "Petroselinum crispum", "easy", ["herb", "edible"], 3, "partial sun", "medium", "monthly", "rich moisture-retentive mix", ["Likes cooler weather"]),
    make_plant("Cilantro", "Coriandrum sativum", "moderate", ["herb", "edible"], 3, "morning sun", "medium", "monthly", "rich well-draining mix", ["Bolts quickly in heat"]),
    make_plant("Sage", "Salvia officinalis", "easy", ["herb", "edible"], 5, "full sun", "low", "monthly diluted", "well-draining herb mix", ["Prune to maintain shape"]),
    make_plant("Chives", "Allium schoenoprasum", "easy", ["herb", "edible"], 4, "full sun", "medium", "monthly", "rich potting mix", ["Cut from the base to regrow"]),
    make_plant("Lavender", "Lavandula angustifolia", "moderate", ["herb", "fragrant"], 7, "full sun", "low", "light feeding in spring", "alkaline sandy mix", ["Needs strong air flow and drainage"]),
    make_plant("Tomato", "Solanum lycopersicum", "moderate", ["vegetable", "balcony"], 2, "full sun", "medium", "weekly tomato feed", "rich compost-heavy mix", ["Stake early", "Check moisture daily in hot weather"]),
    make_plant("Chili Pepper", "Capsicum annuum", "moderate", ["vegetable", "balcony"], 3, "full sun", "medium", "every 2 weeks", "rich well-draining mix", ["Increase potassium during fruiting"]),
    make_plant("Bell Pepper", "Capsicum annuum grossum", "moderate", ["vegetable", "balcony"], 3, "full sun", "medium", "every 2 weeks", "rich well-draining mix", ["Consistent watering prevents blossom-end rot"]),
    make_plant("Eggplant", "Solanum melongena", "moderate", ["vegetable", "balcony"], 3, "full sun", "medium", "every 2 weeks", "rich airy mix", ["Needs warmth and regular feeding"]),
    make_plant("Spinach", "Spinacia oleracea", "easy", ["leafy-green", "edible"], 2, "partial sun", "medium", "light monthly feed", "moisture-retentive fertile mix", ["Prefers cooler weather"]),
    make_plant("Fenugreek", "Trigonella foenum-graecum", "easy", ["leafy-green", "edible"], 2, "full to partial sun", "medium", "light monthly feed", "well-draining fertile mix", ["Fast-growing windowsill edible"]),
    make_plant("Curry Leaf", "Murraya koenigii", "moderate", ["edible", "shrub"], 5, "full sun", "medium", "monthly during warm season", "well-draining fertile mix", ["Protect from cold drafts"]),
    make_plant("Lemongrass", "Cymbopogon citratus", "moderate", ["herb", "fragrant"], 3, "full sun", "medium-high", "every 2 weeks", "rich moisture-retentive mix", ["Thrives in warmth"]),
    make_plant("Rose", "Rosa hybrida", "advanced", ["flowering", "outdoor"], 3, "full sun", "medium", "rose feed every 2 weeks", "rich well-draining loam", ["Deadhead spent blooms", "Monitor for black spot"]),
    make_plant("Hibiscus", "Hibiscus rosa-sinensis", "moderate", ["flowering", "tropical"], 3, "full sun", "medium-high", "every 2 weeks", "rich well-draining mix", ["Drops buds under stress"]),
    make_plant("Marigold", "Tagetes erecta", "easy", ["flowering", "companion"], 3, "full sun", "medium", "monthly", "well-draining mix", ["Deadhead to prolong blooming"]),
    make_plant("Jasmine", "Jasminum sambac", "moderate", ["flowering", "fragrant"], 4, "full to partial sun", "medium", "every 2 weeks in bloom season", "rich airy mix", ["Prune after flowering flushes"]),
    make_plant("Bougainvillea", "Bougainvillea glabra", "advanced", ["flowering", "sun-loving"], 7, "full sun", "low", "monthly bloom feed", "fast-draining gritty mix", ["Blooms best slightly root-bound"]),
    make_plant("Geranium", "Pelargonium zonale", "easy", ["flowering", "balcony"], 4, "full sun", "medium", "every 2 weeks", "well-draining potting mix", ["Remove faded flower heads"]),
    make_plant("Petunia", "Petunia hybrida", "easy", ["flowering", "balcony"], 2, "full sun", "medium", "weekly bloom feed", "fertile well-draining mix", ["Needs regular watering in containers"]),
    make_plant("Aloe Polyphylla", "Aloe polyphylla", "advanced", ["succulent", "collector"], 10, "bright light", "low", "light feeding twice a year", "very gritty mix", ["Needs cool roots and sharp drainage"]),
    make_plant("Money Plant", "Epipremnum aureum", "easy", ["indoor", "vine"], 7, "medium to bright indirect", "medium", "monthly", "well-draining mix", ["Common regional alias for pothos"]),
    make_plant("Croton", "Codiaeum variegatum", "moderate", ["indoor", "colorful"], 5, "bright indirect", "high", "monthly", "rich airy mix", ["Needs stable warmth to keep color"]),
    make_plant("Anthurium", "Anthurium andraeanum", "moderate", ["indoor", "flowering"], 6, "bright indirect", "high", "monthly orchid-strength", "chunky aroid mix", ["Prefers humidity and airflow"]),
    make_plant("Syngonium", "Syngonium podophyllum", "easy", ["indoor", "arrowhead"], 6, "bright indirect", "medium", "monthly", "well-draining mix", ["Can trail or climb"]),
    make_plant("Coleus", "Plectranthus scutellarioides", "easy", ["foliage", "balcony"], 3, "bright filtered", "medium", "every 2 weeks", "rich moist mix", ["Pinch tips to keep compact"]),
    make_plant("Dracaena", "Dracaena fragrans", "easy", ["indoor", "upright"], 8, "medium indirect", "medium", "every 6 weeks", "well-draining indoor mix", ["Sensitive to fluoride buildup"]),
]
